# Generated by Django 3.1.3 on 2021-03-03 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RiskField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('field_type', models.CharField(choices=[('CharField', 'Text'), ('IntegerField', 'Number'), ('DateField', 'Date')], default='CharField', max_length=12)),
                ('kwargs', models.JSONField()),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='insurance.risk')),
            ],
            options={
                'unique_together': {('name', 'risk')},
            },
        ),
    ]
